Lab3/movielens/movielens/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("userview.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lab3/movielens/userview/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("genre/<int:pk>", views.GenreView.as_view(), name="index"),
    path("movie/<int:pk>", views.MovieView.as_view(), name="movie"),
    path("register", views.register_request, name="register"),
    path("log_in", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("my_ratings", views.my_ratings, name="my_ratings"),
    path("new_rating", views.new_rating, name="new_rating"),
    # path("rating", views.RatingView.as_view(), name="rating"),
    path("comment/<int:pk>", views.CommentView.as_view(), name="comment"),
    path("movie/<int:movie_id>/gallery", views.movie_gallery, name="movie_gallery"),
    path("movie/<movie_id>/rate", views.new_rating, name="rate_movie"),
    path("movie/<movie_id>/add_comment", views.add_comment, name="add_comment"),
    path("search", views.search, name="search"),
    path("new_movie", views.new_movie, name="new_movie"),
    path('movie/<int:movie_id>/add_image', views.add_image, name='add_image'),
    path('movie/<int:movie_id>/edit_movie', views.edit_movie, name='edit_movie'),
    path('iframe', views.iframe, name='iframe'),
    path('video_embed', views.video_embed, name='video_embed'),
    path('video/<video_title>', views.video, name='video'),
]

Lab3/movielens/userview/models.py
from django.db import models
from django.conf import settings
from django.db.models import Q, Max, Avg
from embed_video.fields import EmbedVideoField

class Genre(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=1000)
    year = models.IntegerField()
    genres = models.ManyToManyField(Genre)
    director = models.CharField(max_length=1000)
    imdblink = models.URLField(max_length=500)
    description = models.TextField()

    def __str__(self):
        return self.title
    
    def get_most_liked_movies():
        latest_rating_ids = Rating.objects.values('movie').annotate(max_id=Max('id')).order_by('-max_id')
        movie_ids = [rating['movie'] for rating in latest_rating_ids]
        most_liked_movies = Movie.objects.filter(id__in=movie_ids).annotate(avg_rating=Avg('rating__value')).filter(avg_rating__gte=4).order_by('-avg_rating')
        return most_liked_movies
    
    def similar_movies(self):
        similar_movies = Movie.objects.filter(Q(director=self.director) | Q(genres__in=self.genres.all())).exclude(id=self.id).distinct()
        return list(similar_movies)





class Rating(models.Model):
    value = models.FloatField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"Rating {self.rating} for {self.movie}"

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    comment = models.TextField()
    timestamp = models.IntegerField()

    def __str__(self):
        return f"Comment by {self.user.username} on {self.movie}"

class Image(models.Model):
    title = models.CharField(max_length=100)
    img = models.ImageField(upload_to='images/')
    front_image = models.BooleanField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title
    
class EmbeddedVideoItem(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=1000)
    video = EmbedVideoField()
    class Meta:
        ordering = ['title']

Lab3/movielens/userview/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import *

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
class Meta:
    model = User
    fields = ("username", "email", "password1", "password2")
    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    
class RatingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(RatingForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Rating
        fields = ['movie', 'value']

class CommentForm(forms.ModelForm):
    comment = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Enter your comment here', 'rows': 4}),
        label=''
    )
    class Meta:
        model = Comment
        fields = ('comment',)

class SearchForm(forms.Form):
    genres = forms.CharField(required=False)
    title = forms.CharField(required=False)
    min_rating = forms.IntegerField(required=False)
    
class MovieForm(forms.ModelForm):
    genres = forms.ModelMultipleChoiceField(
        queryset=Genre.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    class Meta:
        model = Movie
        fields = ['title', 'year', 'genres', 'director', 'imdblink', 'description']

# class ImageForm(forms.ModelForm):
#     class Meta:
#         model = Image
#         fields = ['title', 'img', 'front_image', 'movie']

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['title', 'img', 'front_image']

    # def __init__(self, movie, *args, **kwargs):
    #     super(ImageForm, self).__init__(*args, **kwargs)
    #     self.movie = movie

    # def save(self, commit=True):
    #     image = super(ImageForm, self).save(commit=False)
    #     image.movie = self.movie
    #     if commit:
    #         image.save()
    #     return image

Lab3/movielens/userview/views.py
# from django.shortcuts import render, get_object_or_404
# from django.http import HttpRequest, HttpResponse
# from django.template import loader
# from .models import Movie, Genre
# def index(request : HttpRequest):
#     movies = Movie.objects.order_by('-title')
#     template = loader.get_template('userview/index.html')
#     context = {
#     'movies' : movies
#     }
#     return HttpResponse(template.render(context,request))
# def view_movie(request: HttpRequest, movie_id):
#     movie = get_object_or_404(Movie, id=movie_id)
#     return render(request, 'userview/movie.html', {'movie': movie})
# def view_genre(request: HttpRequest, genre_id):
#     genre = get_object_or_404(Genre, id=genre_id)
#     movies = Movie.objects.filter(genres=genre)
#     return render(request, 'userview/genre.html', {'genre': genre, 'movies': movies})

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.shortcuts import redirect, render
from django.views import generic
from django.contrib.auth import login, logout, authenticate
from django.db.models import Avg, IntegerField, Q, F, FloatField
from django.db.models.functions import Coalesce
from userview.forms import *
from .models import *
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from datetime import datetime
from django.core.paginator import Paginator
import random

class IndexView(generic.ListView):
    template_name = 'userview/index.html'
    context_object_name = 'movies'
    model = Movie
    def get_queryset(self):
        return Movie.objects.order_by('-title')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Popular lately
        context['most_liked_movies'] = Movie.get_most_liked_movies()
        
        # Similar movies to a random movie rated >= 4 by user
        user = self.request.user if self.request.user.is_authenticated else None
        rated_movies = Rating.objects.filter(user=user, value__gte=4).values_list('movie', flat=True)
        if len(rated_movies) != 0:
            random_good_movie_id = rated_movies[random.randint(0, len(rated_movies)-1)]
            random_good_movie = Movie.objects.get(id=random_good_movie_id)
            context['similar_movies'] = random_good_movie.similar_movies()
        return context
    
class MovieView(generic.DetailView):
    model = Movie
    template_name = 'userview/movie.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        movie = self.get_object()
        comments = Comment.objects.filter(movie=movie)
        context['comments'] = comments
        avg_rating = Rating.objects.filter(movie=movie).aggregate(
            average_rating=Coalesce(Avg('value', output_field=FloatField()), 0.0)
        )['average_rating']
        rounded_rating = round(avg_rating, 1)
        context['avg_rating'] = rounded_rating
        gallery = Image.objects.filter(movie=movie)
        context['gallery'] = gallery.order_by('-front_image', 'id')
        if self.request.user.is_authenticated and Rating.objects.filter(movie=movie, user=self.request.user).first() is not None:
            user_rating = Rating.objects.filter(movie=movie, user=self.request.user).first().value
        else:
            user_rating = 0
        context['user_rating'] = user_rating
        context['comment_form'] = CommentForm()
        
        # Create an instance of ImageForm and pass the movie object
        # context['image_form'] = ImageForm(movie=movie)
        return context
    
class GenreView(generic.DetailView):
    model = Genre
    template_name = 'userview/genre.html'
    
class RatingView(generic.DeleteView):
    model = Rating
    template_name = 'userview/rating.html'
        
class CommentView(generic.DetailView):
    model = Comment
    template_name = 'userview/comment.html'


def register_request(request):
    form = NewUserForm()
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("/")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    return render (request=request, template_name="userview/register.html",
        context={"register_form":form})
    

def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")
    else:
        form = AuthenticationForm()
    return render(request, 'userview/login.html', {'login_form': form})


def logout_request(request):
    logout(request)
    return redirect('/')


def my_ratings(request):
    if request.user.is_authenticated:
        user_ratings = Rating.objects.filter(user=request.user)
        return render(request=request, template_name='userview/my_ratings.html',
                  context={"user_ratings":user_ratings})
    return redirect("/my_ratings")


def new_rating(request, movie_id=None):
    if request.method == 'POST':
        add_form = RatingForm(request.POST)
        if add_form.is_valid():
            user = request.user
            movie = add_form.cleaned_data['movie']
            value = add_form.cleaned_data['value']
            # Check if a rating already exists for the movie and user
            existing_rating = Rating.objects.filter(user=user, movie=movie).first()
            if existing_rating:
                # Update the existing rating
                existing_rating.value = value
                existing_rating.save()
            else:
                # Create a new rating
                rating = add_form.save(commit=False)
                rating.user = user
                rating.value = value
                rating.save()
            return redirect('my_ratings')
    else:
        initial = {}
        if movie_id:
            initial['movie'] = movie_id
            add_form = RatingForm(initial=initial)
            add_form.fields['movie'].initial = movie_id
        else:
            add_form = RatingForm(initial=initial)

    context = {'add_form': add_form}
    return render(request, 'userview/new_rating.html', context)


def movie_gallery(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    gallery = Image.objects.filter(movie=movie)
    context = {
        'movie': movie,
        'gallery': gallery,
    }
    return render(request, template_name='userview/gallery.html', context=context)


def add_comment(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.movie = movie
            now = datetime.now()
            comment.timestamp = now.timestamp()
            comment.save()
            return redirect('/movie/' + str(movie.id))
    else:
        comment_form = CommentForm()
    context = {'comment_form': comment_form, 'movie': movie}
    return render(request, 'userview/add_comment.html', context)


def new_movie(request):
    if request.method == 'POST':
        movie_form = MovieForm(request.POST)
        if movie_form.is_valid():
            movie = movie_form.save()
            return redirect('/movie/' + str(movie.id))
    else:
        movie_form = MovieForm()

    context = {'movie_form': movie_form}
    return render(request, 'userview/new_movie.html', context)


def add_image(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    if request.method == 'POST':
        image_form = ImageForm(request.POST, request.FILES)
        if image_form.is_valid():
            image = image_form.save(commit=False)
            image.movie = movie

            if image.front_image == True:
            # Check if there is an existing front image for the movie
                existing_front_image = Image.objects.filter(movie=movie, front_image=True).first()
                if existing_front_image:
                    # If an existing front image exists, set its front_image attribute to False
                    existing_front_image.front_image = False
                    existing_front_image.save()

            image.save()
            return redirect('/movie/' + str(movie.id))
    else:
        image_form = ImageForm()

    context = {'image_form': image_form}
    return render(request, 'userview/add_image.html', context)


def edit_movie(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    gallery = Image.objects.filter(movie=movie)
    
    if request.method == 'POST':
        if 'delete_movie' in request.POST:
            # Delete the movie
            Movie.objects.filter(id=movie.id).delete()
            return redirect('/')
        
        movie_form = MovieForm(request.POST, instance=movie)
        if movie_form.is_valid():
            movie_form.save()
            return redirect('/movie/' + str(movie.id))
    else:
        movie_form = MovieForm(instance=movie)

    if request.method == 'POST' and 'delete_image' in request.POST:
        image_id = request.POST['delete_image']
        image = get_object_or_404(Image, id=image_id)
        image.delete()
        return HttpResponseRedirect(request.path_info)

    if request.method == 'POST' and 'set_front_image' in request.POST:
        image_id = request.POST['set_front_image']
        image = get_object_or_404(Image, id=image_id)
        

Lab3/movielens/userview/templates/userview/add_comment.html
{% extends "userview/header.html" %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="container py-5">
        <h3>Comment {{ movie.title }}</h3>
        <form method="POST">
            {% csrf_token %}
            {{ comment_form|crispy }}
            <button class="btn btn-success" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

Lab3/movielens/userview/templates/userview/add_image.html
{% extends 'userview/header.html' %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="container py-5">
        <h3>Add Image</h3>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ image_form|crispy }}
            <button class="btn btn-success" type="submit">Add</button>
        </form>
    </div>
{% endblock %}

Lab3/movielens/userview/templates/userview/edit_movie.html
{% extends 'userview/header.html' %}

{% block content %}
{% load crispy_forms_tags %}
    <style>
        .movie-image {
            width: 200px;
            min-height: 157px;
            max-height: 157px;
        }

        .image-card-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            gap: 20px;
        }
        
        .image-card {
            width: 300px;
            border-radius: 10px;
            background-color: #444654;
            text-align: center;
            padding: 20px;
        }
        
        .image-container {
            margin-bottom: 20px;
        }
        
        .movie-image {
            width: 100%;
            height: auto;
            border-radius: 10px;
        }
        
        .image-buttons {
            display: flex;
            justify-content: center;
            gap: 10px;
        }
    </style>

    <div class="container py-5">
        <h1>Edit Movie</h1>
        <form method="post">
            {% csrf_token %}
            {{ movie_form|crispy }}
            <button class="btn btn-success" type="submit">Save</button>
            <button class="btn btn-danger" type="submit" name="delete_movie">Delete Movie</button>
        </form>
        </br>
        <h2>Gallery</h2>
        
        <div class="image-card-container">
            {% for image in gallery.all %}
            <div class="image-card">
                <div class="image-container">
                    <img src="{{ image.img.url }}" alt="Movie Image" class="movie-image">
                </div>
                <div class="image-buttons">
                    {% if not image.front_image %}
                        <form method="post" class="d-inline">
                            {% csrf_token %}
                            <input type="hidden" name="set_front_image" value="{{ image.id }}">
                            <button class="btn btn-success" type="submit">Set Front Image</button>
                        </form>
                    {% endif %}
                    <form method="post" class="d-inline">
                        {% csrf_token %}
                        <input type="hidden" name="delete_image" value="{{ image.id }}">
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>

</br>
</br>
</br>

{% endblock %}

Lab3/movielens/userview/templates/userview/gallery.html
{%extends 'userview/header.html'%}
{% block content %}

<div class="container mt-5">
    <h1>{{ movie.title }}: Gallery<h1>
    <div class="row justify-content-center">
        {% for image in gallery %}
            <div class="col-md-4 mb-3">
                <img src="{{ image.img.url }}" alt="{{ image.title }}"
                style="width: 300px; height: 180px;">
            </div>
        {% endfor %}
    </div>
    <a class="btn btn-primary" href="/movie/{{ movie.id }}">Return to movie</a>
</div>

{% endblock %}

Lab3/movielens/userview/templates/userview/genre.html
{% extends 'userview/header.html' %}
{% block content %}
<div class="container mt-5">
    <h1>{{ genre.name }}</h1>
    <div class="table-responsive">
        <table class="table table-primary">
            <thead>
                <tr>
                    <th scope="col">Movie</th>
                </tr>
            </thead>
            <tbody>
                {%for movie in genre.movie_set.all%}
                <tr class="">
                    <td scope="row"><a href="/movie/{{ movie.id }}">{{movie.title}}</a></td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

Lab3/movielens/userview/templates/userview/header.html
<!doctype html>
<html lang="en">

<head>
  <title>Django</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <link href="https://fonts.cdnfonts.com/css/kenyan-coffee-2" rel="stylesheet">
  {% comment %} <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"> {% endcomment %}

  <style>
    body {
      background-color: #0F0F0F;
    }

    p {
      color: white;
    }

    h1, h2, h3, h4, h5, h6, strong, div {
      color: white;
    }

    .nav-link {
      color: white;
      margin-right: 10px;
    }

    .nav-link:hover {
      color: #000000;
    }

    .navbar {
      width: 100%;
    }

    .card {
      background-color: #444654
    }

    .custom-form {
      color: #444654;
    }

    {% comment %} .form-control{
      background-color: #424452;
    } {% endcomment %}

    .form-control:focus {
      box-shadow: 0 0 0 0.25rem #198754; 
    }

    .form-label {
      color: white;
    }

    .carousel-item img {
      {% comment %} height: 800px;
      object-fit: cover;
      object-position: center top; {% endcomment %}
      max-height: 400px;
      width: auto;
      object-fit: contain;
      object-position: center;
    }
    
    

  </style>
</head>

<body>
  <header>
    <!-- place navbar here -->
    <div class="container-fluid" style="padding-left: 0; padding-right: 0;">
      <nav class="navbar navbar-dark rounded-bottom" style="background-color: #198754">
        <div class="d-flex justify-content-start">
          <a class="nav-link me-3 ms-3" href="/"><i class="fas fa-home"></i></a>
          <a class="nav-link me-3" href="/search"><i class="fas fa-search"></i></a>
          <a class="nav-link me-3" href="/video_embed"><i class="fas fa-film"></i></a>
        </div>
        <div class="d-flex justify-content-center">
          <h3 class="navbar-brand mb-0">Movie Rating Platform</h3>
        </div>
        <div class="d-flex justify-content-end">
          {% if user.is_authenticated %}
          <p class="me-3 mb-0">{{ user.username }}</p>
          <a class="nav-link me-3" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent"><i class="fas fa-user"></i></a>
          {% comment %} <a class="nav-link me-3" href="/my_ratings">My Ratings</a> {% endcomment %}
          {% else %}
          <p class="me-3 mb-0">Guest User</p>
            <a class="nav-link me-3" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent"><i class="fas fa-user"></i></a>
          {% endif %}
        </div>
      </nav>
    </div>
    
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="bg-dark p-4">
        <div class="d-flex justify-content-center">
          {% if user.is_authenticated %}
            <a class="nav-link me-3" href="/logout">Log Out</a>
            <a class="nav-link me-3" href="/my_ratings">My Ratings</a>
            {% if request.user.is_superuser %}
              <a class="nav-link me-3" href="/new_movie">New Movie</a>
            {% endif %}
          {% else %}
            <a class="nav-link me-3" href="/register">Register</a>
            <a class="nav-link me-3" href="/log_in">Log In</a>
          {% endif %}
        </div>
      </div>
    </div>
    
    <script>
      // Add click event listener to the user icon
      document.querySelector('.navbar-toggler').addEventListener('click', function() {
        document.querySelector('#navbarToggleExternalContent').classList.toggle('show');
      });
    </script>
    
    
    
  </header>
  <main>
    {%block content%}

    {%endblock%}
  </main>
  <footer class="bg-dark text-center text-white fixed-bottom">
    {% comment %} {% if user.is_authenticated %}
      <p>You are logged in as {{ user.username }}.</p>
    {% else %}
      <p>You are not logged in.</p>
    {%endif%} {% endcomment %}
    <p>Konefeld & Kopiec</p>
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>
</body>

</html>

Lab3/movielens/userview/templates/userview/iframe.html
{% extends "userview/header.html" %}
{% block content %}
    <head>
        <title>Embedding a Youtube video in a static page</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1,
            shrink-to-fit=no" />
    </head>
        <body>
            <main>
                <iframe width="1237" height="696" src="https://www.youtube.com/embed/Ki_0iES2cGI?controls=0&autoplay=1&mute=1" title="Learn HTML video in 2 minutes 🎥" frameborder="500" allow="accelerometer;
                autoplay;
                clipboard-write;
                encrypted-media;
                gyroscope;
                picture-in-picture;
                web-share" allowfullscreen>
                </iframe>
            </main>
    </body>
{% endblock %}

Lab3/movielens/userview/templates/userview/index.html
{%extends 'userview/header.html'%}
{%block content%}

<div class="row">
    <h1 class="text-center mt-5 mb-4">Welcome!</h1>
</div>
<div class="row justify-content-center">
    <div class="col-sm-3">
        <div class="card">
            <div class="card-body" style="min-height:650px;">
                <h5 class="card-title">Popular Lately:</h5>
                <ul>
                    {% for movie in most_liked_movies|slice:":20" %}
                        <li><a href="/movie/{{ movie.id }}" style="color: white;">{{ movie.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body" style="min-height:650px;">
                <h5 class="card-title">About us:</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Commodo ullamcorper a lacus vestibulum sed arcu. Elit ut aliquam purus sit amet luctus. Pellentesque adipiscing commodo elit at. Semper risus in hendrerit gravida rutrum quisque. Integer enim neque volutpat ac. Dignissim sodales ut eu sem integer vitae. Scelerisque purus semper eget duis at. Lectus quam id leo in vitae turpis massa sed elementum. Congue nisi vitae suscipit tellus. Massa tempor nec feugiat nisl. Dapibus ultrices in iaculis nunc sed augue lacus viverra. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Sapien eget mi proin sed libero enim sed. Nulla aliquet enim tortor at auctor urna nunc. Mi sit amet mauris commodo quis. Ut sem nulla pharetra diam sit amet. Dui faucibus in ornare quam. Vulputate eu scelerisque felis imperdiet proin fermentum leo.</p>
                <p>Orci sagittis eu volutpat odio facilisis mauris sit amet massa. Quam id leo in vitae. Id diam vel quam elementum pulvinar etiam non. Mollis aliquam ut porttitor leo a diam. Tellus integer feugiat scelerisque varius morbi. Sem integer vitae justo eget magna fermentum. Convallis tellus id interdum velit laoreet id donec. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Condimentum lacinia quis vel eros donec ac odio tempor orci. Vel pretium lectus quam id leo in vitae. Et ultrices neque ornare aenean euismod. Amet dictum sit amet justo donec enim diam vulputate.</p>
                <p>Lectus sit amet est placerat in egestas erat imperdiet sed. Nibh tortor id aliquet lectus proin nibh nisl. Turpis massa tincidunt dui ut ornare. Arcu cursus vitae congue mauris rhoncus. Senectus et netus et malesuada.</p>
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="card">
            <div class="card-body" style="min-height:650px;">
                <h5 class="card-title">Recommended movies:</h5>
                {% if user.is_authenticated %}
                    <ul>
                        {% for movie in similar_movies|slice:":20" %}
                            <li><a href="/movie/{{ movie.id }}" style="color: white;">{{ movie.title }}</a></li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>Log in to see recommendations</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
</br>
</br>

{%endblock%}